# Site settings
title: SHTS's Snipet
tag_text: SHTS's Snipet
description: this is my snipets
url: "http://shts.github.io/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

destination: ./_site
